# Generated by Django 2.1 on 2018-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('data', models.TextField(blank=True)),
                ('updated_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
