# Generated by Django 2.1 on 2018-11-10 07:03

import UploadFile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=UploadFile.models.upload_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
