# Generated by Django 2.1 on 2018-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0002_filestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='file_path',
            field=models.FileField(upload_to='Images/'),
        ),
    ]
